%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1920
image_height: 1280
distortion_parameters:
   k1: -0.025
   k2: 0.01
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 1433.0
   fy: 1469.0
   cx: 981.0
   cy: 612.95
